/*
1. 사원의 연봉을 구하는 PL/SQL 블럭 작성, 보너스가 있는 사원은 보너스도 포함하여 계산
2. 구구단 짝수단 출력
	2-1) FOR LOOP
	2-2) WHILE LOOP
*/
DECLARE
    TYPE EMP_NAME_TABLE_TYPE IS TABLE OF EMPLOYEE.EMP_NAME%TYPE
    INDEX BY BINARY_INTEGER;
    TYPE SALARY_TABLE_TYPE IS TABLE OF EMPLOYEE.SALARY%TYPE
    INDEX BY BINARY_INTEGER;
    TYPE BONUS_TABLE_TYPE IS TABLE OF EMPLOYEE.BONUS%TYPE
    INDEX BY BINARY_INTEGER;
    
    EMP_NAME_TABLE EMP_NAME_TABEL_TYPE;
    SALARY_TABLE SALARY_TABLE_TYPE;
    BONUS_TABLE BONUS_TABLE_TYPE;
    
    I BINARY_INTEGER := 0;
BEGIN
    FOR K IN (SELECT EMP_NAME, SALARY, (SALARY*(NVL(BONUS,1)))*12 연봉 FROM EMPLOYEE) LOOP
        I := + 1;
        EMP_NAME_TABLE(I) := K.EMP_NAME;
        SALARY_TABLE(I) := K.SALARY;
        BONUS_TABLE(I) := K.연봉;
    END LOOP;
    FOR J IN 1..I LOOP
        DBMS_OUTPUT.PUT_LINE('사원명 '||EMP_NAME_TABLE(J)||
                            '월급 '|| SALARY_TABLE(J)||
                            '보너스 포함연봉 '|| BONUS_TABLE(J));
    END LOOP;
END;
/
SELECT EMP_NAME, SALARY, (SALARY*(NVL(BONUS,1)))*12 연봉 FROM EMPLOYEE;



DECLARE
    NUM NUMBER := 2;
BEGIN
    FOR K IN 1..9 LOOP
    
    
END;
/
