DROP TABLE TODO;
CREATE TABLE TODO(
    LIST_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000),
    CREATE_AT DATE DEFAULT SYSDATE,
    END_AT DATE,
    STATUS VARCHAR2(10) DEFAULT 'TODO' CHECK (STATUS IN ('TODO', 'DONE'))
);

DROP SEQUENCE TODO_SEQ;
CREATE SEQUENCE TODO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

SELECT * FROM TODO;

SELECT * FROM TODO ORDER BY LIST_NO DESC;
commit;
rollback;
INSERT INTO TODO (LIST_NO, TITLE, CONTENT, STATUS) VALUES (TODO_SEQ.NEXTVAL, '메뉴 정하기', '짜장, 짬뽕', 'TODO');
INSERT INTO TODO (LIST_NO, TITLE, CONTENT, STATUS) VALUES (TODO_SEQ.NEXTVAL, '메뉴 정하기', '제육, 돈까스', 'TODO');
UPDATE TODO SET STATUS = 'DONE' WHERE LIST_NO = 1;