DROP TABLE TODO;
CREATE TABLE TODO (
	LIST_NO	    NUMBER(100),
	TITLE	    VARCHAR2(200)	    NULL,
	CONTENT	    VARCHAR2(2000)		NULL,
	CREATE_AT	DATE		        DEFAULT SYSDATE,
	END_AT	    DATE		        DEFAULT SYSDATE,
	STATUS	    VARCHAR2(4)		    CHECK(TODO OR DONE)
);

CREATE SEQUENCE TODO_SEQ (



DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (    
    USER_NAME   VARCHAR2(30),
    USER_PWD    VARCHAR2(50),
    NICK_NAME   VARCHAR2(50)
);

