/*
    1) 두개 테이블을 만들것(테이블명, 컬럼명(NUMBER, VARCHAR2), 타입, 사이즈, 제약조건)
        PK, NOT NULL, UNIQUE, FK
        테이블 레벨방식으로 제약조건
        CONSTRAINT 제약조건명 제약조건명(PK, NOT, CHECK)(컬럼명)
        CONSTRAINT 제약조건명 제약조건명(FK)(컬럼명) REFERENCE 주테이블(컬럼:PK)
        ON DELETE SET NULL; OR ON DELETE CASCADE;
    2) INSERT 입력 학생테이블 모두 입력, 이후 수강 테이블 등록(FK 제약조건 위해하면 안된다)
    3) 학생 테이블 삭제해본다. (수강테이블에 어떤 사항이 오는지 확인)
    4) 자유주제 테스팅 할것.
*/
DROP TABLE STUDENT;
-- 부모테이블 생성
CREATE TABLE STUDENT(
    STU_ID VARCHAR2(20) NOT NULL,
    STU_NAME VARCHAR2(20),
    STU_MAJOR VARCHAR2(20),
    CONSTRAINT PK_ID PRIMARY KEY(STU_ID)
);

-- 값 대입
INSERT INTO STUDENT VALUES (17123456, '신짱구', '체육');
INSERT INTO STUDENT VALUES (18791011, '김철수', '컴퓨터공학');
INSERT INTO STUDENT VALUES (18121314, '한유리', '행정');
INSERT INTO STUDENT VALUES (19151617, '이훈이', '간호');
INSERT INTO STUDENT VALUES (19181920, '황맹구', '기계공학');
INSERT INTO STUDENT VALUES (19212223, '이흰둥', '국어국문');

SELECT * FROM STUDENT;

DROP TABLE ENROLLMENT;
-- STUDENT 테이블을 참조하는 테이블 생성
CREATE TABLE ENROLLMENT(
    STU_ID VARCHAR2(20),
    STU_ENROLLMENT VARCHAR2(20),
    STU_CREDIT VARCHAR2(20)
);

INSERT INTO ENROLLMENT VALUES (17123456, '01111A', 'A0');
INSERT INTO ENROLLMENT VALUES (18791011, '02222B', 'B+');
INSERT INTO ENROLLMENT VALUES (18121314, '03333C', 'A+');
INSERT INTO ENROLLMENT VALUES (19151617, '01111A', 'B0');
INSERT INTO ENROLLMENT VALUES (19181920, '03333C', 'C+');
INSERT INTO ENROLLMENT VALUES (19212223, '02222B', 'B0');

SELECT * FROM ENROLLMENT;

SELECT * FROM STUDENT, ENROLLMENT;

-- ON DELETE SET NULL
DROP TABLE ENROLLMENT;
CREATE TABLE ENROLLMENT(
    STU_ID VARCHAR2(20),
    STU_ENROLLMENT VARCHAR2(20),
    STU_CREDIT VARCHAR2(20),
    CONSTRAINT PK_FOREIGN_ID PRIMARY KEY(STU_ENROLLMENT),
    CONSTRAINT UK_FOREIGN_NAME UNIQUE(STU_CREDIT),
    CONSTRAINT FK_FOREIGN_ID_ID FOREIGN KEY (STU_ID) 
    REFERENCES STUDENT (STU_ID) ON DELETE SET NULL
);

-- 중복값 변경 
INSERT INTO ENROLLMENT VALUES (17123456, '01111A', 'A0');
INSERT INTO ENROLLMENT VALUES (18791011, '02222B', 'B+');
INSERT INTO ENROLLMENT VALUES (18121314, '03333C', 'A+');
INSERT INTO ENROLLMENT VALUES (19151617, '01112A', 'B0');
INSERT INTO ENROLLMENT VALUES (19181920, '03334C', 'C+');
INSERT INTO ENROLLMENT VALUES (19212223, '02223B', 'C0');

SELECT * FROM ENROLLMENT;

-- DELETE FROM 을 이용한 EMROLLMENT가 참조중인 STUDENT(부모테이블) 데이터 삭제
-- ON DELETE SET NULL
DELETE FROM STUDENT WHERE STU_ID = 17123456;
-- DELETE FROM 후 데이터 확인
SELECT * FROM ENROLLMENT;
-- 삭제한 참조데이터가 null 값으로 변함
--=============================================================================
-- ON DELETE CASCADE
DROP TABLE ENROLLMENT;

CREATE TABLE ENROLLMENT(
    STU_ID VARCHAR2(20),
    STU_ENROLLMENT VARCHAR2(20),
    STU_CREDIT VARCHAR2(20),
    CONSTRAINT PK_FOREIGN_ID PRIMARY KEY(STU_ENROLLMENT),
    CONSTRAINT UK_FOREIGN_NAME UNIQUE(STU_CREDIT),
    CONSTRAINT FK_FOREIGN_ID_ID FOREIGN KEY (STU_ID)
    REFERENCES STUDENT (STU_ID) ON DELETE CASCADE
);

-- 중복값 변경 
INSERT INTO ENROLLMENT VALUES (17123456, '01111A', 'A0');
INSERT INTO ENROLLMENT VALUES (18791011, '02222B', 'B+');
INSERT INTO ENROLLMENT VALUES (18121314, '03333C', 'A+');
INSERT INTO ENROLLMENT VALUES (19151617, '01112A', 'B0');
INSERT INTO ENROLLMENT VALUES (19181920, '03334C', 'C+');
INSERT INTO ENROLLMENT VALUES (19212223, '02223B', 'C0');

SELECT * FROM ENROLLMENT;

-- DELETE FROM 을 사용하여 STUDENT 의 STU_ID 데이터 한가지 제거 (ON DELETE CASCADE)
DELETE FROM STUDENT WHERE STU_ID = 17123456;

-- 삭제된 내용 확인
SELECT * FROM ENROLLMENT;
-- DELETE 된 행의 열의 데이터가 삭제됨 